services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.16
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
      - PGADMIN_CONFIG_ENABLE_PSQL=True
    ports:
      - "5050:80"
    restart: always